GET http://localhost:8080/conf-service/users

###
GET http://localhost:8080/conf-service/users/admin
Requester-Username: admin

###
GET http://localhost:8080/conf-service/users
Requester-Username: admin

###
POST http://localhost:8080/conf-service/users
Requester-Username: admin
Content-Type: application/json; charset: UTF-8

  {
    "username": "admin",
    "email": "admin@gmail.com",
    "status": "ACTIVE"
  }
###
POST http://localhost:8080/conf-service/users
Requester-Username: admin
Content-Type: application/json; charset: UTF-8

{
  "username": "user1",
  "email": "admin@gmail.com",
  "status": "ACTIVE"
}
###
GET http://localhost:8080/conf-service/users
Requester-Username: user1

###
DELETE http://localhost:8080/conf-service/users/user2
Requester-Username: user1

###
DELETE http://localhost:8080/conf-service/users/user1
Requester-Username: user1

###
DELETE http://localhost:8080/conf-service/users/admin
Requester-Username: user1
###
DELETE http://localhost:8080/conf-service/users/user1
Requester-Username: admin
###
GET http://localhost:8080/conf-service/users/user1
Requester-Username: admin
###
POST http://localhost:8080/conf-service/users
Requester-Username: admin
Content-Type: application/json; charset: UTF-8

{
  "username": "viorel",
  "email": "admin@gmail.com",
  "status": "FAIL"
}
