INSERT INTO T_USER_ROLE(role) VALUES('ADMIN');
INSERT INTO T_USER_ROLE(role) VALUES('OPERAT');
INSERT INTO T_USER_ROLE(role) VALUES('CLIENT');

INSERT INTO T_USER_STATUS(status) VALUES('ACTIVE');
INSERT INTO T_USER_STATUS(status) VALUES('SUSPND');
INSERT INTO T_USER_STATUS(status) VALUES('INACTV');