ALTER TABLE T_USER
    ADD CONSTRAINT USER_STATUS_FK FOREIGN KEY (status)
        REFERENCES T_USER_STATUS (status);

ALTER TABLE T_USER
    ADD CONSTRAINT USER_ROLE_FK FOREIGN KEY (role)
        REFERENCES T_USER_ROLE (role);